// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC8QKlog5sDpzj4VoEwAqwcfXw4WCiVDQ',
    appId: '1:764712864508:web:48b3f8ed723f2f95f5a579',
    messagingSenderId: '764712864508',
    projectId: 'obatin-ef71d',
    authDomain: 'obatin-ef71d.firebaseapp.com',
    storageBucket: 'obatin-ef71d.firebasestorage.app',
    databaseURL:
        'https://obatin-ef71d-default-rtdb.asia-southeast1.firebasedatabase.app/',
    measurementId: 'G-ZLZE578L70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwlhm1k9cMTk3f2RQOdz-YbWbgQp_6Ns',
    appId: '1:764712864508:android:165e2c257ec6989df5a579',
    messagingSenderId: '764712864508',
    projectId: 'obatin-ef71d',
    storageBucket: 'obatin-ef71d.firebasestorage.app',
    databaseURL:
        'https://obatin-ef71d-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBh5-hesDVy2DlUAOwMe13v4JbJ5xXmU',
    appId: '1:764712864508:ios:888a3c3186cf7734f5a579',
    messagingSenderId: '764712864508',
    projectId: 'obatin-ef71d',
    storageBucket: 'obatin-ef71d.firebasestorage.app',
    databaseURL:
        'https://obatin-ef71d-default-rtdb.asia-southeast1.firebasedatabase.app/',
    iosBundleId: 'com.example.obat5200411150',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBh5-hesDVy2DlUAOwMe13v4JbJ5xXmU',
    appId: '1:764712864508:ios:888a3c3186cf7734f5a579',
    messagingSenderId: '764712864508',
    projectId: 'obatin-ef71d',
    storageBucket: 'obatin-ef71d.firebasestorage.app',
    databaseURL:
        'https://obatin-ef71d-default-rtdb.asia-southeast1.firebasedatabase.app/',
    iosBundleId: 'com.example.obat5200411150',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC8QKlog5sDpzj4VoEwAqwcfXw4WCiVDQ',
    appId: '1:764712864508:web:33d579f19f177c4bf5a579',
    messagingSenderId: '764712864508',
    projectId: 'obatin-ef71d',
    authDomain: 'obatin-ef71d.firebaseapp.com',
    storageBucket: 'obatin-ef71d.firebasestorage.app',
    databaseURL:
        'https://obatin-ef71d-default-rtdb.asia-southeast1.firebasedatabase.app/',
    measurementId: 'G-44S0FXVT6W',
  );
}
